DROP TABLE IF EXISTS T_SENSOR_SEN;
CREATE TABLE T_SENSOR_SEN (
    SEN_ID BIGINT AUTO_INCREMENT NOT NULL,
    SEN_X INT,
    SEN_Y INT,
    SEN_LAT REAL,
    SEN_LONG REAL,
    SEN_INTENSITY INT,
PRIMARY KEY (SEN_ID_T_SENSOR_SEN));

DROP TABLE IF EXISTS T_FIRESTATION_FST;
CREATE TABLE T_FIRESTATION_FST (
    FST_ID BIGINT AUTO_INCREMENT NOT NULL,
    FST_NAME VARCHAR(30),
    FST_LAT REAL,
    FST_LONG REAL,
PRIMARY KEY (FST_ID));

DROP TABLE IF EXISTS T_FIRETRUCK_FTR ;
CREATE TABLE T_FIRETRUCK_FTR (
    FTR_ID BIGINT AUTO_INCREMENT NOT NULL,
    FTR_NAME VARCHAR(10),
    FTR_LAT REAL,
    FTR_LONG REAL,
    FTR_CAPACITY REAL,
    FTR_RATE REAL,
    FST_ID_T_FIRESTATION BIGINT,
    SEN_ID_T_SENSOR BIGINT,
PRIMARY KEY (FTR_ID_T_FIRETRUCK_FTR));

DROP TABLE IF EXISTS J_FIRESTATION_SENSOR;
CREATE TABLE J_FIRESTATION_SENSOR (
    FST_ID_J_FIRESTATION_FST BIGINT NOT NULL,
    SEN_ID_J_SENSOR_SEN BIGINT NOT NULL,
PRIMARY KEY (FST_ID_J_FIRESTATION_FST, SEN_ID_J_SENSOR_SEN));

ALTER TABLE T_FIRETRUCK_FTR ADD CONSTRAINT FK_T_FIRETRUCK_FTR_FIRESTATION FOREIGN KEY (FST_ID_T_FIRESTATION) REFERENCES T_FIRESTATION_FST (FST_ID);
ALTER TABLE T_FIRETRUCK_FTR ADD CONSTRAINT FK_T_FIRETRUCK_FTR_SENSOR FOREIGN KEY (SEN_ID_T_SENSOR) REFERENCES T_SENSOR_SEN (SEN_ID);

ALTER TABLE J_FIRESTATION_SENSOR ADD CONSTRAINT FK_J_FIRESTATION_SENSOR_FST_ID_T_FIRESTATION_FST FOREIGN KEY (FST_ID_T_FIRESTATION_FST) REFERENCES T_FIRESTATION_FST (FST_ID);
ALTER TABLE J_FIRESTATION_SENSOR ADD CONSTRAINT FK_J_FIRESTATION_SENSOR_SEN_ID_T_SENSOR_SEN FOREIGN KEY (SEN_ID_T_SENSOR_SEN) REFERENCES T_SENSOR_SEN (SEN_ID);